const copy = {
  en: {
    welcomeKicker: "A clearer way to manage property",
    welcomeTitle: "Your Arendnik experience starts here.",
    welcomeCopy: "Choose the role that best describes you. We’ll show you the tools and workflows that matter to your day.",
    chooseLabel: "I’m here as a",
    enter: "Explore this experience",
    changeRole: "Change audience",
    platform: "Platform overview",
    pricing: "Pricing",
    contact: "Contact",
    back: "All audiences",
    roles: [
      {
        name: "Property community",
        descriptor: "For buildings and resident communities",
        kicker: "BUILDING OPERATIONS, IN ONE PLACE",
        title: "A better-running building starts with a clearer view.",
        intro: "Bring resident communication, payments, maintenance requests, and everyday tasks into one organized place.",
        primary: "See how it works",
        secondary: "Explore the platform",
        visualTitle: "Building workspace",
        visualLabels: ["Residents", "Payments", "Requests", "Tasks"],
        visualNote: "Building activity",
        featureTitle: "The everyday work, connected.",
        featureIntro: "Keep building operations visible and easier to coordinate, from one shared workspace.",
        features: [
          ["Resident management", "Keep resident details and communication connected to the building."],
          ["Payments and visibility", "Record payments and keep financial activity easier to follow."],
          ["Service requests", "Receive and monitor maintenance requests in one place."],
          ["Tasks and notifications", "Organize operational follow-ups and keep people informed."],
        ],
        workflowTitle: "From incoming request to clear next step.",
        workflow: ["A resident sends a request", "The team reviews and organizes the work", "Progress and communication stay together"],
        mobileTitle: "Stay close to building operations.",
        mobileCopy: "Check updates, requests, payments, and tasks from your phone, wherever the day takes you.",
        mobileItems: ["Resident communication", "Maintenance requests", "Payments and tasks"],
        ctaTitle: "Bring building management into focus.",
        ctaCopy: "See how Arendnik can support the daily work of your community.",
        mock: ["Building overview", "Residents", "Payment activity", "Service requests", "New request", "In progress", "Task list", "Resident update"],
      },
      {
        name: "Broker / property manager",
        descriptor: "For professionals managing properties and rentals",
        kicker: "YOUR PROPERTY PORTFOLIO, ORGANIZED",
        title: "More properties in view. Fewer details left behind.",
        intro: "Bring property information, tenants, rental agreements, payments, maintenance, and follow-ups into one professional workspace.",
        primary: "See how it works",
        secondary: "Explore the platform",
        visualTitle: "Portfolio workspace",
        visualLabels: ["Properties", "Tenants", "Payments", "Tasks"],
        visualNote: "Rental operations",
        featureTitle: "A working view across every property.",
        featureIntro: "Keep recurring rental work structured and spend less time tracking details by hand.",
        features: [
          ["Property information", "Keep property details and rental information organized together."],
          ["Tenants and agreements", "Manage tenant collaboration and monitor rental agreements."],
          ["Payments and requests", "Track recorded payments alongside maintenance issues and requests."],
          ["Tasks and reminders", "Keep daily follow-ups and important notifications in view."],
        ],
        workflowTitle: "One repeatable rhythm for rental operations.",
        workflow: ["Organize properties and tenant details", "Record agreements, calculations, and payments", "Track requests, messages, and next actions"],
        mobileTitle: "Manage the day between appointments.",
        mobileCopy: "Use mobile access to check property activity, follow requests, and stay in touch with tenants.",
        mobileItems: ["Property and tenant details", "Payment tracking", "Requests and communication"],
        ctaTitle: "Make your portfolio easier to run.",
        ctaCopy: "Bring property and rental operations into one place with Arendnik.",
        mock: ["Portfolio", "Property profile", "Tenant details", "Payment record", "Agreement", "Request status", "Follow-up tasks", "Tenant message"],
      },
      {
        name: "Tenant",
        descriptor: "For people renting a home",
        kicker: "YOUR RENTAL, EASIER TO KEEP UP WITH",
        title: "The important rental details, right at hand.",
        intro: "Check rental information, follow payments, send maintenance requests, and keep in touch with property management from your phone.",
        primary: "Explore the tenant experience",
        secondary: "Explore the platform",
        visualTitle: "Your rental space",
        visualLabels: ["Rental details", "Payments", "Requests", "Messages"],
        visualNote: "Everything in reach",
        featureTitle: "A simpler way to stay on top of renting.",
        featureIntro: "Keep rental-related information and communication together, without chasing separate threads.",
        features: [
          ["Rental information", "Find your rental details and related information in one place."],
          ["Payment tracking", "Review payment information and get reminders about upcoming actions."],
          ["Easy issue reporting", "Send a maintenance request from your phone and attach photos when useful."],
          ["Direct communication", "Stay connected with the property manager through the application."],
        ],
        workflowTitle: "A small request should be simple to make.",
        workflow: ["Open your rental space", "Send a request and add a photo if needed", "Follow updates and communicate in the app"],
        mobileTitle: "Your rental tools, made for mobile.",
        mobileCopy: "Keep payment information, reminders, maintenance requests, and conversations close at hand.",
        mobileItems: ["Rental and payment information", "Requests with photos", "Messages and reminders"],
        ctaTitle: "Make renting feel more straightforward.",
        ctaCopy: "Keep your rental information and conversations together with Arendnik.",
        mock: ["My rental", "Rental information", "Payment history", "Maintenance request", "Add a photo", "Request sent", "Notifications", "Message property manager"],
      },
    ],
  },
  hy: {
    welcomeKicker: "Գույքի կառավարման ավելի հստակ ձև",
    welcomeTitle: "Ձեր Arendnik փորձառությունը սկսվում է այստեղ։",
    welcomeCopy: "Ընտրեք ձեզ համապատասխանող դերը, և կտեսնեք ձեր առօրյա աշխատանքի համար կարևոր գործիքներն ու գործընթացները։",
    chooseLabel: "Ես այստեղ եմ որպես՝",
    enter: "Բացել այս փորձառությունը",
    changeRole: "Փոխել լսարանը",
    platform: "Հարթակի ակնարկ",
    pricing: "Սակագներ",
    contact: "Կապ",
    back: "Բոլոր լսարանները",
    roles: [
      {
        name: "Համատիրություն",
        descriptor: "Շենքերի և բնակիչների համայնքների համար",
        kicker: "ՇԵՆՔԻ ԿԱՌԱՎԱՐՈՒՄ՝ ՄԵԿ ՎԱՅՐՈՒՄ",
        title: "Լավ կառավարվող շենքը սկսվում է հստակ պատկերից։",
        intro: "Բնակիչների հետ կապը, վճարումները, սպասարկման հայտերն ու առօրյա առաջադրանքները միավորեք մեկ կազմակերպված հարթակում։",
        primary: "Տեսնել՝ ինչպես է աշխատում",
        secondary: "Ծանոթանալ հարթակին",
        visualTitle: "Շենքի աշխատանքային տարածք",
        visualLabels: ["Բնակիչներ", "Վճարումներ", "Հայտեր", "Առաջադրանքներ"],
        visualNote: "Շենքի ընթացիկ աշխատանքներ",
        featureTitle: "Առօրյա աշխատանքը՝ փոխկապակցված։",
        featureIntro: "Շենքի գործընթացները դարձրեք տեսանելի և հեշտ համակարգելի՝ մեկ ընդհանուր աշխատանքային տարածքից։",
        features: [
          ["Բնակիչների կառավարում", "Բնակիչների տվյալներն ու հաղորդակցությունը կապեք շենքի հետ։"],
          ["Վճարումներ և տեսանելիություն", "Գրանցեք վճարումները և հետևեք ֆինանսական ընթացքին։"],
          ["Սպասարկման հայտեր", "Ստացեք և վերահսկեք սպասարկման հայտերը մեկ վայրում։"],
          ["Առաջադրանքներ և ծանուցումներ", "Կազմակերպեք ընթացիկ աշխատանքներն ու տեղեկացրեք բնակիչներին։"],
        ],
        workflowTitle: "Դիմումից մինչև հստակ հաջորդ քայլ։",
        workflow: ["Բնակիչն ուղարկում է հայտ", "Թիմը դիտարկում և կազմակերպում է աշխատանքը", "Ընթացքն ու հաղորդակցությունը մնում են միասին"],
        mobileTitle: "Մնացեք շենքի աշխատանքների ընթացքին մոտ։",
        mobileCopy: "Հեռախոսից ստուգեք թարմացումները, հայտերը, վճարումները և առաջադրանքները։",
        mobileItems: ["Կապ բնակիչների հետ", "Սպասարկման հայտեր", "Վճարումներ և առաջադրանքներ"],
        ctaTitle: "Շենքի կառավարումը դարձրեք ավելի հստակ։",
        ctaCopy: "Տեսեք, թե ինչպես կարող է Arendnik-ն աջակցել ձեր համայնքի ամենօրյա աշխատանքին։",
        mock: ["Շենքի ակնարկ", "Բնակիչներ", "Վճարումների ընթացք", "Սպասարկման հայտեր", "Նոր հայտ", "Ընթացքի մեջ", "Առաջադրանքների ցանկ", "Թարմացում բնակիչներին"],
      },
      {
        name: "Բրոքեր / Մենեջեր",
        descriptor: "Գույքեր և վարձակալություն կառավարող մասնագետների համար",
        kicker: "ՁԵՐ ԳՈՒՅՔԵՐԻ ՓԱԹԵԹԸ՝ ԿԱԶՄԱԿԵՐՊՎԱԾ",
        title: "Ավելի շատ գույք՝ տեսադաշտում, ավելի քիչ բաց թողնված մանրուքներ։",
        intro: "Գույքի տվյալները, վարձակալներին, պայմանագրերը, վճարումները, սպասարկումն ու հետագա քայլերը միավորեք մեկ մասնագիտական հարթակում։",
        primary: "Տեսնել՝ ինչպես է աշխատում",
        secondary: "Ծանոթանալ հարթակին",
        visualTitle: "Գույքերի աշխատանքային տարածք",
        visualLabels: ["Գույքեր", "Վարձակալներ", "Վճարումներ", "Առաջադրանքներ"],
        visualNote: "Վարձակալության գործընթացներ",
        featureTitle: "Աշխատանքային պատկեր՝ յուրաքանչյուր գույքի համար։",
        featureIntro: "Կազմակերպեք վարձակալության կրկնվող աշխատանքները և քիչ ժամանակ ծախսեք մանրամասները ձեռքով հետևելու վրա։",
        features: [
          ["Գույքի տվյալներ", "Գույքի և վարձակալության տվյալները պահեք միասին և կազմակերպված։"],
          ["Վարձակալներ և պայմանագրեր", "Կառավարեք վարձակալների հետ համագործակցությունը և հետևեք պայմանագրերին։"],
          ["Վճարումներ և հայտեր", "Հետևեք գրանցված վճարումներին, սպասարկման խնդիրներին ու հայտերին։"],
          ["Առաջադրանքներ և հիշեցումներ", "Պահեք առօրյա քայլերն ու կարևոր ծանուցումները տեսադաշտում։"],
        ],
        workflowTitle: "Վարձակալության գործընթացների մեկ աշխատանքային ռիթմ։",
        workflow: ["Կազմակերպեք գույքերն ու վարձակալների տվյալները", "Գրանցեք պայմանագրերը, հաշվարկներն ու վճարումները", "Հետևեք հայտերին, հաղորդագրություններին և հաջորդ քայլերին"],
        mobileTitle: "Կառավարեք աշխատանքը հանդիպումների արանքում։",
        mobileCopy: "Հեռախոսից ստուգեք գույքի ընթացքը, հետևեք հայտերին և կապ պահպանեք վարձակալների հետ։",
        mobileItems: ["Գույքի և վարձակալի տվյալներ", "Վճարումների վերահսկում", "Հայտեր և հաղորդակցություն"],
        ctaTitle: "Դարձրեք գույքերի կառավարումն ավելի հարմար։",
        ctaCopy: "Գույքի և վարձակալության գործընթացները միավորեք Arendnik-ում։",
        mock: ["Գույքերի ցանկ", "Գույքի տվյալներ", "Վարձակալի տվյալներ", "Վճարման գրառում", "Պայմանագիր", "Հայտի կարգավիճակ", "Հետագա առաջադրանքներ", "Հաղորդագրություն վարձակալից"],
      },
      {
        name: "Վարձակալ",
        descriptor: "Տուն վարձակալող մարդկանց համար",
        kicker: "ՎԱՐՁԱԿԱԼՈՒԹՅԱՆ ՏՎՅԱԼՆԵՐԸ՝ ՁԵՌՔԻ ՏԱԿ",
        title: "Վարձակալության կարևոր տեղեկությունները՝ մեկ հպումով։",
        intro: "Հեռախոսից ստուգեք վարձակալության տվյալները, հետևեք վճարումներին, ուղարկեք սպասարկման հայտեր և կապ պահպանեք գույքի կառավարման պատասխանատուի հետ։",
        primary: "Ծանոթանալ վարձակալի փորձառությանը",
        secondary: "Ծանոթանալ հարթակին",
        visualTitle: "Ձեր վարձակալության տարածքը",
        visualLabels: ["Վարձակալություն", "Վճարումներ", "Հայտեր", "Հաղորդագրություններ"],
        visualNote: "Ամեն ինչ՝ հասանելի",
        featureTitle: "Վարձակալության հարցերը՝ ավելի պարզ։",
        featureIntro: "Վարձակալության հետ կապված տեղեկություններն ու հաղորդակցությունը պահեք միասին՝ առանց տարբեր նամակագրություններ փնտրելու։",
        features: [
          ["Վարձակալության տվյալներ", "Գտեք վարձակալության պայմաններն ու համապատասխան տեղեկությունները մեկ վայրում։"],
          ["Վճարումների վերահսկում", "Դիտեք վճարումների տեղեկությունները և ստացեք առաջիկա գործողությունների հիշեցումներ։"],
          ["Խնդրի հեշտ հաղորդում", "Հեռախոսից ուղարկեք սպասարկման հայտ և անհրաժեշտության դեպքում կցեք լուսանկարներ։"],
          ["Անմիջական հաղորդակցություն", "Հավելվածի միջոցով կապ պահպանեք գույքի կառավարման պատասխանատուի հետ։"],
        ],
        workflowTitle: "Հայտ ուղարկելը պետք է հեշտ լինի։",
        workflow: ["Բացեք ձեր վարձակալության տարածքը", "Ուղարկեք հայտ և անհրաժեշտության դեպքում կցեք լուսանկար", "Հետևեք թարմացումներին և հաղորդակցվեք հավելվածում"],
        mobileTitle: "Վարձակալության գործիքները՝ հեռախոսի համար։",
        mobileCopy: "Վճարումների տվյալները, հիշեցումները, սպասարկման հայտերն ու զրույցները միշտ հասանելի են։",
        mobileItems: ["Վարձակալության և վճարման տվյալներ", "Հայտեր՝ լուսանկարներով", "Հաղորդագրություններ և հիշեցումներ"],
        ctaTitle: "Վարձակալության հարցերը պահեք մեկ տեղում։",
        ctaCopy: "Հավաքեք վարձակալության տեղեկություններն ու հաղորդակցությունը Arendnik-ում։",
        mock: ["Իմ վարձակալությունը", "Վարձակալության տվյալներ", "Վճարումների պատմություն", "Սպասարկման հայտ", "Կցել լուսանկար", "Հայտն ուղարկված է", "Ծանուցումներ", "Հաղորդագրություն կառավարիչին"],
      },
    ],
  },
  ru: {
    welcomeKicker: "Понятное управление недвижимостью",
    welcomeTitle: "Ваш опыт работы с Arendnik начинается здесь.",
    welcomeCopy: "Выберите подходящую роль. Мы покажем инструменты и процессы, важные для вашей повседневной работы.",
    chooseLabel: "Я здесь как",
    enter: "Посмотреть возможности",
    changeRole: "Выбрать другую аудиторию",
    platform: "Обзор платформы",
    pricing: "Тарифы",
    contact: "Контакты",
    back: "Все аудитории",
    roles: [
      {
        name: "Товарищество собственников",
        descriptor: "Для зданий и сообществ жильцов",
        kicker: "УПРАВЛЕНИЕ ЗДАНИЕМ В ОДНОМ МЕСТЕ",
        title: "Эффективная работа здания начинается с ясной картины.",
        intro: "Объедините общение с жильцами, платежи, заявки на обслуживание и повседневные задачи в одном организованном пространстве.",
        primary: "Как это работает",
        secondary: "Обзор платформы",
        visualTitle: "Рабочее пространство здания",
        visualLabels: ["Жильцы", "Платежи", "Заявки", "Задачи"],
        visualNote: "Текущие дела здания",
        featureTitle: "Повседневные дела связаны между собой.",
        featureIntro: "Сделайте процессы здания нагляднее и проще для координации в общем рабочем пространстве.",
        features: [
          ["Работа с жильцами", "Свяжите данные жильцов и общение с конкретным зданием."],
          ["Платежи и прозрачность", "Фиксируйте платежи и следите за финансовыми операциями."],
          ["Заявки на обслуживание", "Получайте и отслеживайте заявки на обслуживание в одном месте."],
          ["Задачи и уведомления", "Организуйте текущие дела и информируйте жильцов."],
        ],
        workflowTitle: "От обращения до понятного следующего шага.",
        workflow: ["Жилец отправляет заявку", "Команда рассматривает и организует работу", "Ход работы и общение остаются вместе"],
        mobileTitle: "Будьте в курсе дел здания.",
        mobileCopy: "Проверяйте обновления, заявки, платежи и задачи с телефона, где бы вы ни находились.",
        mobileItems: ["Общение с жильцами", "Заявки на обслуживание", "Платежи и задачи"],
        ctaTitle: "Сделайте управление зданием понятнее.",
        ctaCopy: "Узнайте, как Arendnik может поддержать повседневную работу сообщества.",
        mock: ["Обзор здания", "Жильцы", "Платежи", "Заявки на обслуживание", "Новая заявка", "В работе", "Список задач", "Обновление для жильцов"],
      },
      {
        name: "Брокер / менеджер",
        descriptor: "Для специалистов по недвижимости и аренде",
        kicker: "ПОРТФЕЛЬ ОБЪЕКТОВ ПОД КОНТРОЛЕМ",
        title: "Больше объектов в поле зрения. Меньше упущенных деталей.",
        intro: "Объедините сведения об объектах, арендаторах, договорах, платежах, обслуживании и дальнейших действиях в одном рабочем пространстве.",
        primary: "Как это работает",
        secondary: "Обзор платформы",
        visualTitle: "Рабочее пространство портфеля",
        visualLabels: ["Объекты", "Арендаторы", "Платежи", "Задачи"],
        visualNote: "Операции по аренде",
        featureTitle: "Рабочая картина по каждому объекту.",
        featureIntro: "Систематизируйте регулярные процессы аренды и тратьте меньше времени на ручное отслеживание деталей.",
        features: [
          ["Информация об объектах", "Храните сведения об объектах и аренде вместе."],
          ["Арендаторы и договоры", "Работайте с арендаторами и следите за договорами аренды."],
          ["Платежи и заявки", "Отслеживайте платежи, вопросы обслуживания и заявки."],
          ["Задачи и напоминания", "Держите текущие дела и важные уведомления в поле зрения."],
        ],
        workflowTitle: "Единый ритм для процессов аренды.",
        workflow: ["Организуйте объекты и данные арендаторов", "Фиксируйте договоры, расчёты и платежи", "Следите за заявками, сообщениями и дальнейшими действиями"],
        mobileTitle: "Управляйте делами между встречами.",
        mobileCopy: "Проверяйте активность объектов, заявки и общение с арендаторами с телефона.",
        mobileItems: ["Данные об объектах и арендаторах", "Контроль платежей", "Заявки и общение"],
        ctaTitle: "Упростите работу с портфелем.",
        ctaCopy: "Объедините управление объектами и арендой в Arendnik.",
        mock: ["Портфель", "Профиль объекта", "Данные арендатора", "Платёж", "Договор", "Статус заявки", "Текущие задачи", "Сообщение арендатора"],
      },
      {
        name: "Арендатор",
        descriptor: "Для тех, кто снимает жильё",
        kicker: "ВАША АРЕНДА ПОД РУКОЙ",
        title: "Важная информация об аренде всегда рядом.",
        intro: "Проверяйте сведения об аренде, следите за платежами, отправляйте заявки на обслуживание и общайтесь с управляющей стороной с телефона.",
        primary: "Возможности для арендаторов",
        secondary: "Обзор платформы",
        visualTitle: "Ваше пространство аренды",
        visualLabels: ["Аренда", "Платежи", "Заявки", "Сообщения"],
        visualNote: "Всё под рукой",
        featureTitle: "Больше порядка в вопросах аренды.",
        featureIntro: "Храните сведения об аренде и общение вместе, не разыскивая отдельные переписки.",
        features: [
          ["Сведения об аренде", "Находите информацию об аренде и связанные сведения в одном месте."],
          ["Контроль платежей", "Просматривайте платежную информацию и получайте напоминания о действиях."],
          ["Простая отправка заявки", "Отправляйте заявку на обслуживание с телефона и при необходимости прикрепляйте фото."],
          ["Прямая связь", "Общайтесь с управляющей стороной через приложение."],
        ],
        workflowTitle: "Отправить заявку должно быть просто.",
        workflow: ["Откройте своё пространство аренды", "Отправьте заявку и при необходимости добавьте фото", "Следите за обновлениями и общайтесь в приложении"],
        mobileTitle: "Инструменты арендатора в телефоне.",
        mobileCopy: "Информация о платежах, напоминания, заявки и переписка всегда под рукой.",
        mobileItems: ["Данные об аренде и платежах", "Заявки с фотографиями", "Сообщения и напоминания"],
        ctaTitle: "Пусть вопросы аренды решаются проще.",
        ctaCopy: "Храните сведения об аренде и общение в Arendnik.",
        mock: ["Моя аренда", "Информация об аренде", "История платежей", "Заявка на обслуживание", "Добавить фото", "Заявка отправлена", "Уведомления", "Сообщение управляющему"],
      },
    ],
  },
};

export default copy;